### ISSUE TITLE
Have a separate model for LN similar to Motion

### ISSUE THREAD

**Issue by Eve-ning** [Eve-ning/osutools#19]

**Comment by Eve-ning** [comment]
```
well say you use per-column hold difficulty thing
0 is not held 1 is held
1 1 1 0 0 0 0
gives no difficulty increase
while other combinations give difficulty increase
like 1 1 0 0 1 0
```
robby250

**Comment by robby250** [comment]
- LNoteHead: same as a regular note
- LNoteTail: 0.2 of a note for LNs shorter than 0.1 sec, up to 1 note for LNs longer than 0.5 sec
- LNoteBody:
Keep track of which buttons are held, separate columns per hand.
Whenever a Note or LNoteHead is pressed, or LNoteTail is released, check whether outward, inward or both wrist rotations are blocked for that press and increase difficulty accordingly: 1.3x outward blocked, 1.5x inward blocked, 1.8x both.
If there are multiple LNs blocking a certain wrist rotation then it's sort of redundant but still useful to keep track of them and increase difficulty by 0.1x. For example, if inward wrist rotation is blocked by 2 LNs instead of 1, then increase the difficulty by 1.6x instead of 1.5x.
If within a short timeframe* there are notes on the same hand where the player must alternate quickly between outward, inward and finger muscles then difficulty increases futher. Quick alternation between a note that has outward rotation blocked and another note that has inward rotation blocked usually means that there's a LN in between the notes and it's harder to press them, so in this example instead of increasing difficulty by 1.3x for the outward blocked note and 1.5x for inward blocked note, the whole pattern is increased in difficulty by 1.8x.
*This timeframe should depend on the static difficulty of the map. For easy maps it could be as high as 500ms and for hard maps it could be 100ms.
In order to prevent stacked LN presses/releases spiking difficulty, LNoteBody should start being tracked roughly 80ms after LNoteHead is pressed and end 80 ms before LNoteTail is released (Or whatever the great timing window is on the outer border).
The numbers are just for the sake of example and can be fine tuned later after implementation.
